version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    ports:
      - "61616:61616"  # JMS port
      - "8161:8161"    # Web console
      - "61613:61613"  # STOMP port
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - activemq_data:/var/lib/artemis-instance
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  activemq_data:
  redis_data: